//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatewayServiceTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("47ba-636899680566020891.apps.signserviceapi.com")]
        public string APP_ID {
            get {
                return ((string)(this["APP_ID"]));
            }
            set {
                this["APP_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NTdkZmZhNTg-MTVmOC00N2Jh")]
        public string APP_SECRET {
            get {
                return ((string)(this["APP_SECRET"]));
            }
            set {
                this["APP_SECRET"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sample.vnpt.enterprise@vnpt.vn")]
        public string ENTERPRISE_ACC {
            get {
                return ((string)(this["ENTERPRISE_ACC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sample.vnpt.02@vnpt.vn")]
        public string USER_ACC {
            get {
                return ((string)(this["USER_ACC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456a@A")]
        public string USER_PASS {
            get {
                return ((string)(this["USER_PASS"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.vnpt-ca.vn/signservice/v4/api_gateway")]
        public string SERVICE_URL {
            get {
                return ((string)(this["SERVICE_URL"]));
            }
            set {
                this["SERVICE_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.vnpt-ca.vn/signservice/v4/oauth/token")]
        public string SERVICE_GET_TOKENURL {
            get {
                return ((string)(this["SERVICE_GET_TOKENURL"]));
            }
            set {
                this["SERVICE_GET_TOKENURL"] = value;
            }
        }
    }
}
