//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace testSigning_Winform.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RemoteSigningService_v2Soap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserCertificate[]))]
    public partial class RemoteSigningService_v2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Authorize authorizeValueField;
        
        private System.Threading.SendOrPostCallback UserAuthorizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCertificate_VNPTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFileSignOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RemoteSigningService_v2() {
            this.Url = global::testSigning_Winform.Properties.Settings.Default.testSigning_Winform_localhost_RemoteSigningService_v2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Authorize AuthorizeValue {
            get {
                return this.authorizeValueField;
            }
            set {
                this.authorizeValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UserAuthorizeCompletedEventHandler UserAuthorizeCompleted;
        
        /// <remarks/>
        public event GetCertificate_VNPTCompletedEventHandler GetCertificate_VNPTCompleted;
        
        /// <remarks/>
        public event SendFileSignCompletedEventHandler SendFileSignCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthorizeValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserAuthorize", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ERS_Response UserAuthorize(string userName, string Md5Password) {
            object[] results = this.Invoke("UserAuthorize", new object[] {
                        userName,
                        Md5Password});
            return ((ERS_Response)(results[0]));
        }
        
        /// <remarks/>
        public void UserAuthorizeAsync(string userName, string Md5Password) {
            this.UserAuthorizeAsync(userName, Md5Password, null);
        }
        
        /// <remarks/>
        public void UserAuthorizeAsync(string userName, string Md5Password, object userState) {
            if ((this.UserAuthorizeOperationCompleted == null)) {
                this.UserAuthorizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAuthorizeOperationCompleted);
            }
            this.InvokeAsync("UserAuthorize", new object[] {
                        userName,
                        Md5Password}, this.UserAuthorizeOperationCompleted, userState);
        }
        
        private void OnUserAuthorizeOperationCompleted(object arg) {
            if ((this.UserAuthorizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAuthorizeCompleted(this, new UserAuthorizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthorizeValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCertificate_VNPT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ERS_Response GetCertificate_VNPT(string userName, string password, string uid, string serialNumber) {
            object[] results = this.Invoke("GetCertificate_VNPT", new object[] {
                        userName,
                        password,
                        uid,
                        serialNumber});
            return ((ERS_Response)(results[0]));
        }
        
        /// <remarks/>
        public void GetCertificate_VNPTAsync(string userName, string password, string uid, string serialNumber) {
            this.GetCertificate_VNPTAsync(userName, password, uid, serialNumber, null);
        }
        
        /// <remarks/>
        public void GetCertificate_VNPTAsync(string userName, string password, string uid, string serialNumber, object userState) {
            if ((this.GetCertificate_VNPTOperationCompleted == null)) {
                this.GetCertificate_VNPTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCertificate_VNPTOperationCompleted);
            }
            this.InvokeAsync("GetCertificate_VNPT", new object[] {
                        userName,
                        password,
                        uid,
                        serialNumber}, this.GetCertificate_VNPTOperationCompleted, userState);
        }
        
        private void OnGetCertificate_VNPTOperationCompleted(object arg) {
            if ((this.GetCertificate_VNPTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCertificate_VNPTCompleted(this, new GetCertificate_VNPTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthorizeValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendFileSign", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ERS_Response SendFileSign(RemoteSigningProvider signProvider, string uid, string username, string password, HoSoInfo hoso, string serialNumber) {
            object[] results = this.Invoke("SendFileSign", new object[] {
                        signProvider,
                        uid,
                        username,
                        password,
                        hoso,
                        serialNumber});
            return ((ERS_Response)(results[0]));
        }
        
        /// <remarks/>
        public void SendFileSignAsync(RemoteSigningProvider signProvider, string uid, string username, string password, HoSoInfo hoso, string serialNumber) {
            this.SendFileSignAsync(signProvider, uid, username, password, hoso, serialNumber, null);
        }
        
        /// <remarks/>
        public void SendFileSignAsync(RemoteSigningProvider signProvider, string uid, string username, string password, HoSoInfo hoso, string serialNumber, object userState) {
            if ((this.SendFileSignOperationCompleted == null)) {
                this.SendFileSignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFileSignOperationCompleted);
            }
            this.InvokeAsync("SendFileSign", new object[] {
                        signProvider,
                        uid,
                        username,
                        password,
                        hoso,
                        serialNumber}, this.SendFileSignOperationCompleted, userState);
        }
        
        private void OnSendFileSignOperationCompleted(object arg) {
            if ((this.SendFileSignCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFileSignCompleted(this, new SendFileSignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Authorize : System.Web.Services.Protocols.SoapHeader {
        
        private string secretKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string SecretKey {
            get {
                return this.secretKeyField;
            }
            set {
                this.secretKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ToKhaiInfo {
        
        private string maToKhaiField;
        
        private string tenToKhaiField;
        
        private string tenFileField;
        
        private FileType typeField;
        
        private byte[] dataField;
        
        /// <remarks/>
        public string MaToKhai {
            get {
                return this.maToKhaiField;
            }
            set {
                this.maToKhaiField = value;
            }
        }
        
        /// <remarks/>
        public string TenToKhai {
            get {
                return this.tenToKhaiField;
            }
            set {
                this.tenToKhaiField = value;
            }
        }
        
        /// <remarks/>
        public string TenFile {
            get {
                return this.tenFileField;
            }
            set {
                this.tenFileField = value;
            }
        }
        
        /// <remarks/>
        public FileType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum FileType {
        
        /// <remarks/>
        PDF,
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        OFFICE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ThongTinDonVi {
        
        private string tenDonViField;
        
        private string maSoThueField;
        
        private string maDonViField;
        
        private string coQuanBHXHField;
        
        private string nguoiKyField;
        
        private string dienThoaiField;
        
        private int loaiDoiTuongField;
        
        /// <remarks/>
        public string TenDonVi {
            get {
                return this.tenDonViField;
            }
            set {
                this.tenDonViField = value;
            }
        }
        
        /// <remarks/>
        public string MaSoThue {
            get {
                return this.maSoThueField;
            }
            set {
                this.maSoThueField = value;
            }
        }
        
        /// <remarks/>
        public string MaDonVi {
            get {
                return this.maDonViField;
            }
            set {
                this.maDonViField = value;
            }
        }
        
        /// <remarks/>
        public string CoQuanBHXH {
            get {
                return this.coQuanBHXHField;
            }
            set {
                this.coQuanBHXHField = value;
            }
        }
        
        /// <remarks/>
        public string NguoiKy {
            get {
                return this.nguoiKyField;
            }
            set {
                this.nguoiKyField = value;
            }
        }
        
        /// <remarks/>
        public string DienThoai {
            get {
                return this.dienThoaiField;
            }
            set {
                this.dienThoaiField = value;
            }
        }
        
        /// <remarks/>
        public int LoaiDoiTuong {
            get {
                return this.loaiDoiTuongField;
            }
            set {
                this.loaiDoiTuongField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HoSoInfo {
        
        private string guidHSField;
        
        private string maHoSoField;
        
        private string tenThuTucField;
        
        private System.DateTime ngayLapField;
        
        private ThongTinDonVi donViField;
        
        private ToKhaiInfo[] toKhaisField;
        
        /// <remarks/>
        public string GuidHS {
            get {
                return this.guidHSField;
            }
            set {
                this.guidHSField = value;
            }
        }
        
        /// <remarks/>
        public string MaHoSo {
            get {
                return this.maHoSoField;
            }
            set {
                this.maHoSoField = value;
            }
        }
        
        /// <remarks/>
        public string TenThuTuc {
            get {
                return this.tenThuTucField;
            }
            set {
                this.tenThuTucField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayLap {
            get {
                return this.ngayLapField;
            }
            set {
                this.ngayLapField = value;
            }
        }
        
        /// <remarks/>
        public ThongTinDonVi DonVi {
            get {
                return this.donViField;
            }
            set {
                this.donViField = value;
            }
        }
        
        /// <remarks/>
        public ToKhaiInfo[] ToKhais {
            get {
                return this.toKhaisField;
            }
            set {
                this.toKhaisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChainData {
        
        private string ca_certField;
        
        private object root_certField;
        
        /// <remarks/>
        public string ca_cert {
            get {
                return this.ca_certField;
            }
            set {
                this.ca_certField = value;
            }
        }
        
        /// <remarks/>
        public object root_cert {
            get {
                return this.root_certField;
            }
            set {
                this.root_certField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserCertificate {
        
        private string service_typeField;
        
        private string service_nameField;
        
        private string cert_idField;
        
        private string cert_statusField;
        
        private string serial_numberField;
        
        private string cert_subjectField;
        
        private System.DateTime cert_valid_fromField;
        
        private System.DateTime cert_valid_toField;
        
        private string cert_dataField;
        
        private ChainData chain_dataField;
        
        private string transaction_idField;
        
        /// <remarks/>
        public string service_type {
            get {
                return this.service_typeField;
            }
            set {
                this.service_typeField = value;
            }
        }
        
        /// <remarks/>
        public string service_name {
            get {
                return this.service_nameField;
            }
            set {
                this.service_nameField = value;
            }
        }
        
        /// <remarks/>
        public string cert_id {
            get {
                return this.cert_idField;
            }
            set {
                this.cert_idField = value;
            }
        }
        
        /// <remarks/>
        public string cert_status {
            get {
                return this.cert_statusField;
            }
            set {
                this.cert_statusField = value;
            }
        }
        
        /// <remarks/>
        public string serial_number {
            get {
                return this.serial_numberField;
            }
            set {
                this.serial_numberField = value;
            }
        }
        
        /// <remarks/>
        public string cert_subject {
            get {
                return this.cert_subjectField;
            }
            set {
                this.cert_subjectField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime cert_valid_from {
            get {
                return this.cert_valid_fromField;
            }
            set {
                this.cert_valid_fromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime cert_valid_to {
            get {
                return this.cert_valid_toField;
            }
            set {
                this.cert_valid_toField = value;
            }
        }
        
        /// <remarks/>
        public string cert_data {
            get {
                return this.cert_dataField;
            }
            set {
                this.cert_dataField = value;
            }
        }
        
        /// <remarks/>
        public ChainData chain_data {
            get {
                return this.chain_dataField;
            }
            set {
                this.chain_dataField = value;
            }
        }
        
        /// <remarks/>
        public string transaction_id {
            get {
                return this.transaction_idField;
            }
            set {
                this.transaction_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ERS_Response {
        
        private string messageField;
        
        private bool successField;
        
        private UserCertificate[] certificatesField;
        
        private string dataField;
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public UserCertificate[] certificates {
            get {
                return this.certificatesField;
            }
            set {
                this.certificatesField = value;
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum RemoteSigningProvider {
        
        /// <remarks/>
        VNPT,
        
        /// <remarks/>
        VietTel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UserAuthorizeCompletedEventHandler(object sender, UserAuthorizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAuthorizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAuthorizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ERS_Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ERS_Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetCertificate_VNPTCompletedEventHandler(object sender, GetCertificate_VNPTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCertificate_VNPTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCertificate_VNPTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ERS_Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ERS_Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendFileSignCompletedEventHandler(object sender, SendFileSignCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFileSignCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFileSignCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ERS_Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ERS_Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591